(function attachV3ResearchData(root) {
  'use strict';

  root.V3_RESEARCH_DATA = {
    version: '2026-07-21-v3.0',
    asOf: '2026-07-21',
    scope: '2021–2026 H1',
    methodology: {
      externalLayer: '政府、研究机构或明确转述行业数据库的外部基准；仅作市场定位，不并入项目具名样本。',
      namedLayer: '项目内 78 笔具名交易（34 笔核心库 + 44 笔候选转正扩展）；用于解释买方、阶段、条款和资产来源，不代表全球 census。',
      scenarioLayer: 'Base / Bull / Bear 为条件路径，不输出未经历史校准的单点概率。',
    },
    benchmarks: [
      {
        id: 'RB-001', theme: 'MARKET CYCLE', metric: '全球生命科学 M&A 总额', value: '$240B',
        comparison: '+81% vs 2024 $130B', period: 'FY2025',
        source: 'EY M&A Firepower 2026', tier: 'T1 · 原发布方研究',
        url: 'https://www.ey.com/en_gl/newsroom/2026/01/life-sciences-m-a-spending-accelerates-as-the-industry-faces-growth-gaps-and-looks-to-ai-and-china-for-innovation',
        caveat: '包含 biopharma 与 medtech；签约价值不等于已完成交割现金。',
      },
      {
        id: 'RB-002', theme: 'MARKET CYCLE', metric: '全球生命科学 M&A 笔数变化', value: '-12%',
        comparison: 'Biopharma -19% / Medtech +6%', period: 'FY2025',
        source: 'EY M&A Firepower 2026', tier: 'T1 · 原发布方研究',
        url: 'https://www.ey.com/en_gl/newsroom/2026/01/life-sciences-m-a-spending-accelerates-as-the-industry-faces-growth-gaps-and-looks-to-ai-and-china-for-innovation',
        caveat: '需与金额上升并读；说明回暖集中而非普遍放量。',
      },
      {
        id: 'RB-003', theme: 'MARKET CYCLE', metric: 'M&A 平均单笔投资', value: '$2.1B',
        comparison: '+107% vs 2024', period: 'FY2025',
        source: 'EY M&A Firepower 2026', tier: 'T1 · 原发布方研究',
        url: 'https://www.ey.com/en_gl/newsroom/2026/01/life-sciences-m-a-spending-accelerates-as-the-industry-faces-growth-gaps-and-looks-to-ai-and-china-for-innovation',
        caveat: '算术均值易受 megadeal 影响；不等于中位数。',
      },
      {
        id: 'RB-004', theme: 'BUYER CAPACITY', metric: '行业 Firepower', value: '$2.1T',
        comparison: '创纪录', period: '2026 outlook',
        source: 'EY M&A Firepower 2026', tier: 'T1 · 原发布方研究',
        url: 'https://www.ey.com/en_gl/newsroom/2026/01/life-sciences-m-a-spending-accelerates-as-the-industry-faces-growth-gaps-and-looks-to-ai-and-china-for-innovation',
        caveat: '并购容量模型；不是行业现金余额或年度预算。',
      },
      {
        id: 'RB-005', theme: 'BUYER CAPACITY', metric: 'Top 25 药企增长缺口', value: '$370B',
        comparison: '$100B by 2028', period: '2032 outlook',
        source: 'EY M&A Firepower 2026', tier: 'T1 · 原发布方研究',
        url: 'https://www.ey.com/en_gl/newsroom/2026/01/life-sciences-m-a-spending-accelerates-as-the-industry-faces-growth-gaps-and-looks-to-ai-and-china-for-innovation',
        caveat: '预测值；受管线读出、价格政策和汇率影响。',
      },
      {
        id: 'RB-006', theme: 'ORIGIN SHIFT', metric: '中国占美欧联盟投资额份额', value: '34%',
        comparison: '4% in 2020', period: 'FY2025',
        source: 'EY M&A Firepower 2026', tier: 'T1 · 原发布方研究',
        url: 'https://www.ey.com/en_gl/newsroom/2026/01/life-sciences-m-a-spending-accelerates-as-the-industry-faces-growth-gaps-and-looks-to-ai-and-china-for-innovation',
        caveat: '不是全球 BD 金额份额、交易笔数份额或已支付现金份额。',
      },
      {
        id: 'RB-007', theme: 'RISK ALLOCATION', metric: 'R&D 授权披露总额', value: '$250.2B / 516 deals',
        comparison: '2016 以来最高', period: 'FY2025',
        source: 'J.P. Morgan Q4 2025 · DealForma', tier: 'T1 · 原发布方研究',
        url: 'https://www.jpmorgan.com/content/dam/jpmorgan/documents/cb/insights/outlook/jpm-biopharma-deck-q4-2025.pdf',
        caveat: 'Headline value 包含大量里程碑；不是确定性现金。',
      },
      {
        id: 'RB-008', theme: 'RISK ALLOCATION', metric: 'H1 R&D 授权披露总额', value: '$166.7B',
        comparison: 'Upfront cash 6%', period: '2026 H1',
        source: 'J.P. Morgan Q2 2026 · DealForma', tier: 'T1 · 原发布方研究',
        url: 'https://www.jpmorgan.com/insights/markets-and-economy/outlook/biopharma-medtech-deal-reports',
        caveat: '不可与 M&A 总额相加后称为去重全球市场规模。',
      },
      {
        id: 'RB-009', theme: 'RISK ALLOCATION', metric: 'H1 授权 upfront cash 占总额', value: '6%',
        comparison: '7% in FY2025', period: '2026 H1',
        source: 'J.P. Morgan Q2 2026 · DealForma', tier: 'T1 · 原发布方研究',
        url: 'https://www.jpmorgan.com/insights/markets-and-economy/outlook/biopharma-medtech-deal-reports',
        caveat: '不是单笔中位数；非首付部分不等于同一兑现概率。',
      },
      {
        id: 'RB-010', theme: 'MARKET CYCLE', metric: 'H1 Biopharma M&A', value: '$96B / 80 deals',
        comparison: 'Q2 $55.1B / 48 deals', period: '2026 H1',
        source: 'J.P. Morgan Q2 2026 · DealForma', tier: 'T1 · 原发布方研究',
        url: 'https://www.jpmorgan.com/insights/markets-and-economy/outlook/biopharma-medtech-deal-reports',
        caveat: '定义与 EY 的全生命科学 M&A 不同。',
      },
      {
        id: 'RB-011', theme: 'ORIGIN SHIFT', metric: '中国创新药对外授权', value: '约 $110B / 81 deals',
        comparison: '达到 2025 全年总额的 80%', period: '2026 H1',
        source: '国家药监局 · 国家医保局转载', tier: 'T0 · 政府',
        url: 'https://www.nhsa.gov.cn/art/2026/7/14/art_14_21423.html',
        caveat: '逐笔清单和已到账现金未公开；交易总额为 headline value。',
      },
      {
        id: 'RB-012', theme: 'EXECUTION CAPABILITY', metric: '连续收购者年均 TSR', value: '12.2%',
        comparison: '不活跃收购者 0.3%', period: '2012–2022',
        source: 'Bain Global M&A Report 2025', tier: 'T1 · 原发布方研究',
        url: 'https://www.bain.com/insights/healthcare-and-life-sciences-m-and-a-report-2025/',
        caveat: '公司长期 TSR 的相关性证据；不是单笔并购回报或因果估计。',
      },
      {
        id: 'RB-013', theme: 'MARKET CYCLE', metric: '全口径生命科学 BD 总额', value: '$606B / 4,341 deals',
        comparison: '2024 $421B / 3,883 deals', period: 'FY2025',
        source: 'BIO News · 转述 DealForma', tier: 'T1_ATTRIBUTED · 带出处转述',
        url: 'https://bio.news/bio-convention/big-summit-experts-see-signs-of-ma-momentum-in-2026/',
        caveat: '非纯 M&A；二手转述；不可与 M&A 或授权总额相加。',
      },
    ],
    findings: [
      {
        id: 'RF-001', theme: 'MARKET CYCLE', title: '回暖是集中式而非普涨', evidence: ['RB-001', 'RB-002', 'RB-003', 'RB-010'], confidence: 'HIGH',
        fact: 'EY 报告 2025 M&A 金额增长 81% 但笔数下降 12%；J.P. Morgan 报告 H1 2026 Biopharma M&A 为 $96B / 80 笔。',
        inference: '资本向近商业化和稀缺 best-in-class 资产集中；headline 市场回暖不等于普通资产流动性同步改善。',
        counter: '均值和总额可能被少数 megadeal 拉高；EY 与 J.P. Morgan 的样本定义也不同。',
        action: '筛选时同时看交易笔数、中位数、资产阶段和签约/完成状态，优先近商业化与稀缺资产。',
      },
      {
        id: 'RF-002', theme: 'RISK ALLOCATION', title: 'Headline value 与确定性价值继续分离', evidence: ['RB-007', 'RB-008', 'RB-009'], confidence: 'HIGH',
        fact: '2025 R&D 授权披露总额 $250.2B / 516 笔；2026 H1 已达 $166.7B，但 upfront cash 仅占 6%。',
        inference: '买方把更多临床、注册和商业化风险后移；卖方的真实融资价值取决于 upfront、非或有付款、里程碑可达性和 royalty。',
        counter: '低比例也可能由多资产或平台交易抬高最大里程碑包导致；不必然代表单笔条款恶化。',
        action: '逐笔拆分 upfront / non-contingent / contingent / royalty，以确定性现金和里程碑质量比较真实条款。',
      },
      {
        id: 'RF-003', theme: 'ORIGIN SHIFT', title: '中国成为结构性创新供给池', evidence: ['RB-006', 'RB-011'], confidence: 'HIGH',
        fact: '国家药监局统计 H1 2026 中国创新药对外授权约 $110B / 81 笔；EY 报告中国占美欧联盟投资额 34%。',
        inference: '中国资产已从成本套利来源转为全球管线补充的重要供给端；跨境 BD 将长期化。',
        counter: '两个指标的分母不同且 headline value 不等于现金；全球注册、CMC、IP、地缘合规和数据可重复性仍可能压低兑现率。',
        action: '在价格之外建立全球试验质量、注册路径、制造、权益范围和合规清单。',
      },
      {
        id: 'RF-004', theme: 'EXECUTION CAPABILITY', title: '交易能力比交易次数更重要', evidence: ['RB-012', 'RB-001'], confidence: 'MEDIUM HIGH',
        fact: 'Bain 样本中 2012–2022 年连续收购者年均 TSR 12.2%，不活跃公司 0.3%；EY 称只有 32% 交易达到至少 100% 预期收入目标。',
        inference: '可重复的标的筛选、治疗领域邻接、尽调和整合能力，更可能解释长期回报差异。',
        counter: '频繁收购者可能本来就更优质；样本覆盖医疗健康与生命科学而非纯 biopharma；相关性不能当成因果。',
        action: '买方画像加入既有治疗领域、过往整合、管线承载力和资本纪律，优先识别具备可复制交易能力的收购者。',
      },
    ],
    scenarios: [
      {
        id: 'RS-BASE', label: '基准：高选择性延续', window: '2026 H2–2028',
        trigger: '专利悬崖与 Firepower 持续，但资本市场只部分修复。',
        market: '总额保持强势而笔数有限；后期和 best-in-class 稀缺溢价延续；授权继续 milestone-heavy。',
        asset: '硬数据和全球开发路径决定 upfront；me-too 与拥挤资产折价。',
        indicators: ['季度 M&A 金额与笔数分化', 'Upfront ratio 维持中低个位数', 'Phase 2/3 资产竞价'],
        invalidation: '连续两个季度金额与笔数同时显著下滑，且 IPO / 融资继续恶化。',
      },
      {
        id: 'RS-BULL', label: '上行：流动性向中段扩散', window: '2026 H2–2028',
        trigger: 'IPO 与后续融资重开、监管可见度改善、临床读出成功率上行。',
        market: '竞价从近商业化资产扩散到临床早中期平台；更多 non-contingent 与 co-development。',
        asset: '有差异化机制和可全球开发数据的早期资产获得更高确定性现金。',
        indicators: ['IPO 数量与融资广度', '中位 upfront 上升', '多买家竞价与跨境 co-co 增加'],
        invalidation: '融资重开只集中在少数 AI 或大型项目，且中位条款不改善。',
      },
      {
        id: 'RS-BEAR', label: '下行：风险再次后移', window: '2026 H2–2028',
        trigger: '关键临床失败、地缘或监管收紧、药价和融资压力叠加。',
        market: '大额 M&A 仍可能脉冲出现，但广度收缩；option / NewCo / CVR 比例上升。',
        asset: '早期资产 headline 维持，但 upfront 和控制权走弱；现金跑道成为谈判约束。',
        indicators: ['交易撤回率', '独家期权与 CVR 使用', '中国跨境审批与合规周期', 'Biotech cash runway'],
        invalidation: '高质量跨境交易持续缩短签约周期，且 upfront / 非或有付款同步上升。',
      },
    ],
  };
})(typeof globalThis !== 'undefined' ? globalThis : window);
